# Generated by Django 4.0.4 on 2024-06-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0)),
                ('recieved_amount', models.FloatField(default=0)),
                ('total_due', models.FloatField(default=0.0)),
                ('current_plan', models.IntegerField(blank=True, choices=[(0, '1 Month'), (1, '2 Month'), (2, '3 Month'), (3, '4 Month'), (4, '5 Month'), (5, '6 Month'), (6, '7 Month'), (7, '8 Month'), (8, '9 Month'), (9, '10 Month'), (10, '11 Month'), (11, '12 Month')], null=True)),
                ('joining_date', models.DateField(auto_now_add=True, null=True)),
                ('subscription_start_date', models.DateField(blank=True, default=None, null=True)),
                ('subscription_end_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=250, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=600, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=250, null=True)),
                ('purpose', models.CharField(blank=True, max_length=250, null=True)),
                ('timing', models.CharField(blank=True, max_length=250, null=True)),
                ('total_payment', models.FloatField(default=0.0)),
                ('paid_payment', models.FloatField(default=0.0)),
                ('due', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, max_length=600, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=250, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('dance_style', models.CharField(blank=True, max_length=250, null=True)),
                ('batch', models.IntegerField(choices=[(0, 'Morning batch'), (1, 'Evening Batch'), (2, 'Zumba')], default=0)),
                ('timing', models.IntegerField(choices=[(0, '05:00 am - 06:00 am'), (1, '06:00 am - 07:00 am'), (2, '07:00 am - 08:00 am'), (3, '08:00 am - 09:00 am'), (4, '09:00 am - 10:00 am'), (5, '10:00 am - 11:00 am'), (6, '11:00 am - 12:00 pm'), (7, '12:00 pm - 01:00 pm'), (8, '01:00 pm - 02:00 pm'), (9, '02:00 pm - 03:00 pm'), (10, '03:00 pm - 04:00 pm'), (11, '04:00 pm - 05:00 pm'), (12, '05:00 pm - 06:00 pm'), (13, '06:00 pm - 07:00 pm'), (14, '07:00 pm - 08:00 pm'), (15, '08:00 pm - 09:00 pm'), (16, '09:00 pm - 10:00 pm')], default=0)),
                ('any_medical_problem', models.BooleanField(default=False)),
                ('medical_certificate', models.FileField(blank=True, max_length=250, null=True, upload_to='Dance Academy/medical certificate/')),
                ('identity_proof_type', models.IntegerField(blank=True, choices=[(0, 'Adhar'), (1, 'Pan card'), (2, 'Driving license'), (4, 'Voter Id')], default=0, null=True)),
                ('identity_proof_file', models.FileField(blank=True, max_length=250, null=True, upload_to='Dance Academy/identify proof/')),
                ('noc_document', models.FileField(blank=True, max_length=250, null=True, upload_to='Dance Academy/noc document/')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('student_photo', models.FileField(blank=True, max_length=250, null=True, upload_to='Dance Academy/student photo/')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscription_start_date', models.DateField(blank=True, default=None, null=True)),
                ('subscription_end_date', models.DateField(blank=True, default=None, null=True)),
                ('current_plan', models.IntegerField(blank=True, choices=[(0, '1 Month'), (1, '2 Month'), (2, '3 Month'), (3, '4 Month'), (4, '5 Month'), (5, '6 Month'), (6, '7 Month'), (7, '8 Month'), (8, '9 Month'), (9, '10 Month'), (10, '11 Month'), (11, '12 Month')], null=True)),
                ('total_fees', models.FloatField(default=0.0)),
                ('paid_fees', models.FloatField(default=0.0)),
                ('due', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('parent_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='last_log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountlog'),
        ),
        migrations.AddField(
            model_name='account',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
